version: '1'
services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_PASSWORD=password
      # - POSTGRES_USER=root
    ports :
      - "5432:5432"
    volumes:
      - ./server/script.sql:/script.sql
  web:
    build: dockerfile/site
    ports :
      - "80:80"
    volumes:
      - ./www:/var/www/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

  serveur_smtp:
    image: namshi/smtp:latest
    restart : always
    ports:
      - "1025:25"  
    environment:
      - SMTP_USERNAME=votre_email@gmail.com
      - SMTP_PASSWORD=votre_mot_de_passe
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
    networks:
      - default