version: '1'
services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./server/script.sql:/docker-entrypoint-initdb.d/init-script.sql
  web:
    build: dockerfile/site
    ports :
      - "80:80"
    volumes:
      - ./www:/var/www/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db