/:
  controller: FrontOffice/Main
  action: home
  template: front

/login:
  controller: FrontOffice/Security
  action: login
  restricted: false

/logout:
  controller: FrontOffice/Security
  action: logout
  restricted: false

/register:
  controller: FrontOffice/Security
  action: register
  restricted: false

/dashboard/users:
  controller: BackOffice/User
  action: listUsers
  template: back
  restricted: true
  roles:
    - admin
    - author
    - user