#/:
#  controller: FrontOffice/Main
#  action: home
#  template: front

/guide:
  controller: FrontOffice/Main
  action: designGuide
  template: front

/login:
  controller: FrontOffice/Security
  action: login
  restricted: false
  template: front

/logout:
  controller: FrontOffice/Security
  action: logout
  restricted: false

/register:
  controller: FrontOffice/Security
  action: register
  restricted: false
  template: front

/validate-account:
  controller: FrontOffice/Security
  action: validateAccount
  restricted: false

/reset-password-request:
  controller: FrontOffice/Security
  action: resetPasswordRequest
  restricted: false
  template: front

/reset-password:
  controller: FrontOffice/Security
  action: resetPassword
  restricted: false
  template: front

/account:
  controller: FrontOffice/UserAccount
  action: userAccount
  restricted: false
  template: front

/change-password:
  controller: FrontOffice/UserAccount
  action: changePassword
  template: front

/deactivate-account:
  controller: FrontOffice/UserAccount
  action: deactivateAccount
  template: front

/delete-account:
  controller: FrontOffice/UserAccount
  action: deleteAccount
  template: front

/dashboard:
  controller: BackOffice/Charts
  action: listCharts
  template: back
  restricted: true
  roles: [1]

/dashboard/pages/builder/:idPage:
  controller: BackOffice/Editor
  action: pageBuilder
  template: back
  params:
    - idPage
  restricted: true
  roles: [1]

/dashboard/articles/builder/:idArticle:
  controller: BackOffice/Articles
  action: articlesBuilder
  template: back
  params:
    - idArticle
  restricted: true
  roles: [1, 2, 3]

/dashboard/articles:
  controller: BackOffice/Articles
  action: getAllArticles
  template: back



/dashboard/pages:
  controller: BackOffice/Pages
  action: getPagesList
  template: back
  restricted: true
  roles: [1]

/dashboard/pages/create:
  controller: BackOffice/Pages
  action: createNewPage
  restricted: true
  roles: [1]

/dashboard/pages/delete/:id:
  controller: BackOffice/Pages
  action: deletePage
  params:
    - id
  restricted: true
  roles: [1]


/dashboard/settings:
  controller: BackOffice/Settings
  action: getSettings
  template: back
  restricted: true
  roles: [1]

/dashboard/settings/update:
  controller: BackOffice/Settings
  action: getCurrentValuesAction
  template: back
  restricted: true
  roles: [1]

/dashboard/builder-save-article:
  controller: BackOffice/Articles
  action: saveArticle
  restricted: true
  roles: [1, 2, 3]

/dashboard/builder/last-articles:
  controller: BackOffice/Editor
  action: lastArticles

/dashboard/builder-save-page:
  controller: BackOffice/Editor
  action: savePage
  restricted: true
  roles: [1]




/dashboard/users:
  controller: BackOffice/User
  action: listUsers
  template: back
  restricted: true
  roles: [1]

/dashboard/users/create:
  controller: BackOffice/User
  action: createUser
  template: back
  restricted: true
  roles: [1]

/dashboard/users/edit/:id:
  controller: BackOffice/User
  action: editUser
  template: back
  params:
    - id
  restricted: true
  roles: [1]

/dashboard/users/show/:id:
  controller: BackOffice/User
  action: showUser
  template: back
  params:
    - id
  restricted: true
  roles: [1]

/dashboard/users/delete/:id:
  controller: BackOffice/User
  action: deleteUser
  template: back
  params:
    - id
  restricted: true
  roles: [1]

/dashboard/users/delete/confirm/:id:
  controller: BackOffice/User
  action: deleteUser
  template: back
  params:
    - id
  restricted: true
  roles: [1]

/dashboard/articles/categories:
  controller: BackOffice/Category
  action: listCategories
  template: back
  restricted: true
  roles: [1]

/dashboard/articles/categories/create:
  controller: BackOffice/Category
  action: createCategory
  template: back
  restricted: true
  roles: [1]

/dashboard/articles/categories/edit/:id:
  controller: BackOffice/Category
  action: editCategory
  template: back
  params:
    - id
  restricted: true
  roles: [1]

/dashboard/articles/categories/show/:id:
  controller: BackOffice/Category
  action: showCategory
  template: back
  params:
    - id
  restricted: true
  roles: [1]

/dashboard/articles/categories/delete/:id:
  controller: BackOffice/Category
  action: deleteCategory
  template: back
  params:
    - id
  restricted: true
  roles: [1]

/dashboard/articles/categories/delete/confirm/:id:
  controller: BackOffice/Category
  action: deleteCategory
  template: back
  params:
    - id
  restricted: true
  roles: [1]

/dashboard/comments/create:
  controller: BackOffice/Comments
  action: createComment
  restricted: true
  roles: [1]
  
/article/:idArticle:
  controller: BackOffice/Articles
  action: articlesPage
  template: front
  params:
    - idArticle
