/:
  controller: FrontOffice/Main
  action: home
  template: front

/guide:
  controller: FrontOffice/Main
  action: designGuide
  template: front

/login:
  controller: FrontOffice/Security
  action: login
  restricted: false

/logout:
  controller: FrontOffice/Security
  action: logout
  restricted: false

/register:
  controller: FrontOffice/Security
  action: register
  restricted: false

/dashboard:
  controller: BackOffice/Dashboard
  action: pageDashboard

/dashboard/builder:
  controller: BackOffice/Editor
  action: pageBuilder

/dashboard/users:
  controller: BackOffice/User
  action: listUsers
  template: back
  restricted: true
  roles:
    - admin
    - modo
    - author
    - user