#/:
#  controller: FrontOffice/Main
#  action: home
#  template: front

/guide:
  controller: FrontOffice/Main
  action: designGuide
  template: front

/login:
  controller: FrontOffice/Security
  action: login
  restricted: false
  template: front

/logout:
  controller: FrontOffice/Security
  action: logout
  restricted: false

/register:
  controller: FrontOffice/Security
  action: register
  restricted: false
  template: front

/validate-account:
  controller: FrontOffice/Security
  action: validateAccount
  restricted: false

/reset-password-request:
  controller: FrontOffice/Security
  action: resetPasswordRequest
  restricted: false
  template: front

/reset-password:
  controller: FrontOffice/Security
  action: resetPassword
  restricted: false
  template: front

/dashboard:
  controller: BackOffice/Main
  action: home
  template: back

/dashboard/articles:
  controller: BackOffice/Articles
  action: getAllArticles
  template: back

/dashboard/builder-save-article:
  controller: BackOffice/Articles
  action: saveArticle

#/dashboard/builder:
#  controller: BackOffice/Editor
#  action: pageBuilder

/dashboard/builder/last-articles:
  controller: BackOffice/Editor
  action: lastArticles

/dashboard/builder-save-page:
  controller: BackOffice/Editor
  action: savePage



/dashboard/users:
  controller: BackOffice/User
  action: listUsers
  template: back